# Site settings
title: Grecia
description: >
  Dive into the glittering sea from a sailing boat and catch the sunset on the way back to shore - you’ll soon see why this is a destination fit for gods.
baseurl: "/grecia" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json]
